# Generated by Django 3.1.7 on 2021-04-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
