# Generated by Django 3.1.7 on 2021-04-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210408_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'SportWear'), ('OW', 'OutWear')], default='p', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default='P'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('P', 'primary'), ('D', 'danger')], default='p', max_length=2),
            preserve_default=False,
        ),
    ]
